export interface Course {
  id: string;
  universityName: string;
  courseName: string;
  country: string;
  duration: string;
  intake: string;
  annualTuition: string;
  estimatedLivingCost: string;
  entryRequirements: string;
  englishRequirement: string;
  scholarshipAvailable: string;
  reasonForMatch?: string; // Optional reasoning generated by the AI Matcher
  ranking: string;
  popularityScore?: number; // 1-100 scale for comparison display
  employabilityRate?: string; // e.g. "96%"
}

export interface StudentApplication {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  passportNumber: string;
  dateOfBirth: string;
  highestQualification: string;
  gradesSummary: string;
  englishProficiency: string; // e.g. "IELTS 6.5"
  desiredCourseId: string;
  desiredCourseName: string;
  desiredUniversity: string;
  desiredCountry: string;
  intakeSeason: string; // e.g. "Sept 2026"
  status: "Submitted" | "Verified" | "Offer_Issued" | "Deposit_Paid" | "Visa_Lodged" | "Approved";
  notes?: string;
  createdAt: string;
}

export interface MatchmakerInput {
  grades: string;
  fieldOfStudy: string;
  destination: string;
  budget: string;
  englishProficiency: string;
}

export interface SuccessStory {
  id: string;
  studentName: string;
  originCountry: string;
  destinationUniversity: string;
  courseName: string;
  placedYear: string;
  testimonial: string;
  currentRole?: string;
  studentImage?: string;
}
